format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# Configure the hostname module
[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold purple"

[directory]
style = "bold blue"

[git_branch]
format = "[$branch]($style)"
style = "bold red"

[cmd_duration]
disabled = true

[python]
format = "[$virtualenv]($style) "
style = "purple"

